name: checkerboard
version: '0.1'
summary: checkerboard
description: |
 Checkerboard is C program to generate checker image file with pmg format.
 to run as example, $ ./checkerboard checker_vga.pgm
  
grade: stable
confinement: strict

apps:
  checkerboard:
    command: checkerboard

parts:
  checkerboard:
    plugin: autotools
    source: https://github.com/h1fujiwara/checkerboard.git
    build-packages:
      - build-essential


