
  name: checkerboard
  version: '0.1'
  summary: checkerboard
  description: |
    Checkerboard is C program to generate checker image file with pmg format.
    to run as example, $ ./checkerboard checker_vga.pgm

  grade: devel
  confinement: devmode
  
  parts:
    checkerboard:
      plugin: make
      source-type: zip
      source: https://github.com/h1fujiwara/checkerboard/archive/master.zip
      build-packages:
      - build-essential      
  
